### PR TITLE
Add configuration option to disallow tooltips to close on normal events

### PR DESCRIPTION
**Pull request by mike-engel**
Spawned from #20

### CODE REVIEW

**Comment by jacobsvante** [comment]
Hey Mike,

Thanks for looking at this. I tested your latest changes and the tests seem to be working better now. I noticed two things however:

I changed the timeout period to [10 times of the originally specified time](https://github.com/jmagnusson/isotip/commit/8eef1a6cff4b5e84a7add394be15ab5bba210c41) on one of the `autoClose` tests and that made it fail. Shouldn't it stay visible until it's programmatically closed?

When I use it in one of my own apps and click outside of the tooltip it still closes. I used the following configuration (on a regular element with no `data-tooltip-*` attributes or `tooltip-*` classes added):

``` javascript
  isotip.open(
    '#my-element', {
      title: 'hello',
      content: 'world',
      autoClose: false
    }
  )
```

**Comment by mike-engel** [comment]
Thanks @jmagnusson. Sorry for the run-around here—It's been a while since I've worked on Isotip and there are a lot of race conditions with the tests. With your tests, did it close only when passing `autoClose`, or also with the `data-tooltip-autoclose` attribute as well? In my testing, the attribute worked fine, and I've got an idea of how to fix the `autoClose` option.

**Comment by jacobsvante** [comment]
So it was a timeout causing the problems. Sorry for not noticing that.

Anyways everything seems to be working well now except for when clicking outside the `autoClose: false` spawned tooltip. Should be an easy fix, right?

**Comment by jacobsvante** [comment]
Fixed `autoClose: false` not being respected in #30

**Comment by mike-engel** [comment]
Thanks @jmagnusson. The main problem now, is that if there's an open tooltip that can't be closed normally, but the user opens another tooltip, then the first one won't scroll with the page, if that makes sense. There are two solutions I see to this:
1. Prevent the opening of other tooltips until the one with `autoClose: false` is closed
2. Add more logic to scroll more than one tooltip at a time, if they're open

Thoughts?

**Comment by jacobsvante** [comment]
I'd be okay with any solution. Just document it if you go with the first one :blush:

**Comment by mike-engel** [comment]
Alrighty @jmagnusson! Just wrapped up some final edits. When you get a chance, take a look and make sure it's working for you and the API looks good. Once you're good with it, I'll get it merged in and released as `1.3.0`. Thanks!

**Comment by jacobsvante** [comment]
It seems to be working fine except one thing. If I try to close the tooltip with isotip.close('selector') it will instead remove the element. Closing by passing in the element works fine. See this example. https://jsfiddle.net/3pa4kf2x/1/

**Comment by mike-engel** [comment]
Hey @jmagnusson sorry for the delay. Looking at this now, it's actually working correctly. The selector that's meant to be passed in is the tooltip itself, not the trigger. That's pretty confusing in hindsight, but it's also why passing in the tooltip element works, but the selector in your example doesn't. I forked your example and it now works correctly: https://jsfiddle.net/vbkLpywd

I think in isotip 2.0, I'm going to change the API to only accept DOM elements and not strings as selectors, which will clear a lot of this up. If you have any thoughts on this, let me know.

**Comment by jacobsvante** [comment]
Alright, I understand. So this PR should be good to go I think :-)

**Comment by mike-engel** [comment]
Merged and published as 1.3.0. Thanks @jmagnusson!

**Comment by jacobsvante** [comment]
And thank you for working on this!

**Pull request merged**
