### PR TITLE
data-tooltip-timeout

### PR DESCRIPTION
**Pull request by sjlu**
Added in the ability to close a tooltip after a set amount of time using default options or an attribute `data-tooltip-timeout`

### CODE REVIEW

**Comment by mike-engel** [comment]
@sjlu This looks pretty good. Can you write some tests for it?

**Comment by sjlu** [comment]
@mike-engel wrote a basic test, it covers to make sure the element still exists within `1/2 * timeout` time and checks to see if it's removed after `timeout + isotip.options.removalDelay + 1`

**Comment by mike-engel** [comment]
Thanks @sjlu. Could you also add a test to make sure the `data-tooltip-timeout` attribute works as well?

Additionally, it would be good to store the timeout as `self.currentTimeout` and cancel that timeout if the tooltip closes before the timeout fires.

**Comment by mike-engel** [comment]
Closing this PR as this project is no longer being maintained.

**Pull request closed without merging**
